"""Build the Windows installer:  dist/ModernMidiPlayer-Setup-<version>.exe

Works on Windows (with NSIS installed: https://nsis.sourceforge.io) or on
Linux/macOS with a native makensis.  Requires Pillow for the artwork.

    python installer/build_installer.py [--makensis PATH]

What it bundles
  * the app (midiplayer package, demos, SoundFont)
  * a private 64-bit CPython (python-build-standalone) - no system Python needed
  * FluidSynth DLLs (high-quality software synth)
PySide6 is downloaded by the installer at install time (pip).
"""
import argparse
import hashlib
import os
import shutil
import subprocess
import sys
import tarfile
import urllib.request
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BUILD = os.path.join(HERE, "build")
STAGE = os.path.join(BUILD, "stage")
CACHE = os.path.join(HERE, "cache")
DIST = os.path.join(ROOT, "dist")

PYTHON_URL = ("https://github.com/astral-sh/python-build-standalone/releases/download/20241016/"
              "cpython-3.12.7+20241016-x86_64-pc-windows-msvc-install_only.tar.gz")
FLUID_URL = "https://github.com/FluidSynth/fluidsynth/releases/download/v2.3.4/fluidsynth-2.3.4-win10-x64.zip"

sys.path.insert(0, ROOT)
from midiplayer import __version__  # noqa: E402

NOTICES = f"""Modern MIDI Player {__version__}
============================================================

This installer contains or downloads the following components:

Python 3.12 runtime (python-build-standalone)
  Python Software Foundation License - https://docs.python.org/3/license.html
  Build: https://github.com/astral-sh/python-build-standalone

FluidSynth 2.3.4 software synthesizer (with GLib, libsndfile, libinstpatch,
GCC runtime libraries)
  GNU Lesser General Public License v2.1 - https://www.gnu.org/licenses/lgpl-2.1.html
  Source: https://github.com/FluidSynth/fluidsynth

TimGM6mb.sf2 General MIDI SoundFont
  (c) 2004 Tim Brechbill, 2010 David Bolton
  GNU General Public License v2 - https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
  Source: https://github.com/musescore/musescore-old

Qt for Python (PySide6-Essentials) and Qt 6 - downloaded from PyPI during setup
  GNU Lesser General Public License v3 - https://www.qt.io/licensing
  Source: https://code.qt.io/cgit/pyside/pyside-setup.git

python-rtmidi (optional, downloaded from PyPI during setup)
  MIT License - https://github.com/SpotlightKid/python-rtmidi

Everything is installed for the current user only. Uninstall at any time from
Settings > Apps > Installed apps.
"""


def fetch(url):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, url.rsplit("/", 1)[1].replace("%2B", "+"))
    if not os.path.exists(path):
        print("downloading", url)
        with urllib.request.urlopen(url) as r, open(path + ".part", "wb") as f:
            shutil.copyfileobj(r, f)
        os.replace(path + ".part", path)
    return path


def ignore_junk(_dir, names):
    return [n for n in names if n in ("__pycache__",) or n.endswith((".pyc", ".pdb"))]


def stage_python():
    dst = os.path.join(STAGE, "python")
    tmp = os.path.join(BUILD, "py_extract")
    shutil.rmtree(tmp, ignore_errors=True)
    with tarfile.open(fetch(PYTHON_URL)) as t:
        t.extractall(tmp)
    src = os.path.join(tmp, "python")
    # trim what a GUI app never needs
    for rel in ("tcl", "include", "libs", "Lib/test", "Lib/idlelib", "Lib/tkinter", "Lib/turtledemo",
                "Lib/turtle.py", "Lib/lib2to3/tests", "DLLs/_tkinter.pyd", "DLLs/tcl86t.dll", "DLLs/tk86t.dll",
                "Lib/ensurepip"):
        p = os.path.join(src, *rel.split("/"))
        if os.path.isdir(p):
            shutil.rmtree(p)
        elif os.path.exists(p):
            os.remove(p)
    shutil.copytree(src, dst, ignore=ignore_junk)
    shutil.rmtree(tmp)


def stage_fluidsynth(app_dir):
    dst = os.path.join(app_dir, "fluidsynth")
    os.makedirs(dst, exist_ok=True)
    with zipfile.ZipFile(fetch(FLUID_URL)) as z:
        for name in z.namelist():
            if name.startswith("bin/") and name.lower().endswith(".dll"):
                with z.open(name) as s, open(os.path.join(dst, os.path.basename(name)), "wb") as d:
                    shutil.copyfileobj(s, d)


def stage_app(update_repo: str = ""):
    app = os.path.join(STAGE, "app")
    shutil.copytree(os.path.join(ROOT, "midiplayer"), os.path.join(app, "midiplayer"), ignore=ignore_junk)
    # bake the update source into the installed copy
    with open(os.path.join(app, "midiplayer", "update_config.py"), "w", encoding="utf-8") as f:
        f.write('"""Generated by installer/build_installer.py"""\n'
                f"GITHUB_REPO = {update_repo!r}\n")
    for d in ("demos", "soundfonts"):
        shutil.copytree(os.path.join(ROOT, d), os.path.join(app, d), ignore=ignore_junk)
    for f in ("run.py", "README.md"):
        shutil.copy2(os.path.join(ROOT, f), app)
    with open(os.path.join(app, "THIRD-PARTY-NOTICES.txt"), "w", encoding="utf-8", newline="\r\n") as f:
        f.write(NOTICES)
    stage_fluidsynth(app)


def find_makensis(arg):
    if arg:
        return arg
    for c in ("makensis", r"C:\Program Files (x86)\NSIS\makensis.exe", r"C:\Program Files\NSIS\makensis.exe"):
        if shutil.which(c) or os.path.exists(c):
            return shutil.which(c) or c
    sys.exit("makensis not found - install NSIS (https://nsis.sourceforge.io) or pass --makensis")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--makensis", default=os.environ.get("MAKENSIS", ""))
    from midiplayer.update_config import GITHUB_REPO
    ap.add_argument("--update-repo",
                    default=os.environ.get("MMP_UPDATE_REPO") or os.environ.get("GITHUB_REPOSITORY") or GITHUB_REPO,
                    help="GitHub owner/repo whose Releases the installed app checks for updates")
    args = ap.parse_args()
    makensis = find_makensis(args.makensis)

    shutil.rmtree(BUILD, ignore_errors=True)
    os.makedirs(STAGE)
    os.makedirs(DIST, exist_ok=True)
    sys.path.insert(0, HERE)
    import make_images
    make_images.main(BUILD)
    stage_app(args.update_repo)
    print('update source:', args.update_repo or '(none - in-app updates disabled)')
    stage_python()

    defines = [f"-DVERSION={__version__}", f"-DOUTDIR={DIST}", f"-DBUILDDIR={BUILD}", f"-DSTAGEDIR={STAGE}"]
    for script in ("launcher.nsi", "installer.nsi"):
        cmd = [makensis, "-V2", *defines, os.path.join(HERE, script)]
        print(" ".join(cmd))
        subprocess.check_call(cmd)
    out = os.path.join(DIST, f"ModernMidiPlayer-Setup-{__version__}.exe")
    h = hashlib.sha256()
    with open(out, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    with open(out + ".sha256", "w", encoding="ascii", newline="\n") as f:
        f.write(f"{h.hexdigest()}  {os.path.basename(out)}\n")
    print(f"\nbuilt {out}  ({os.path.getsize(out) / 1e6:.1f} MB)\nsha256 {h.hexdigest()}")


if __name__ == "__main__":
    main()
